    dependencies:
      flutter:
        sdk: flutter
      
      tflite_flutter: ^0.10.4
      image_picker: ^1.0.7
      image: ^4.1.7 
      
      cupertino_icons: ^1.0.2

    flutter:
      uses-material-design: true
      assets:
        - assets/best_float32.tflite
        - assets/labels.txt
